@startuml
hide circle
skinparam classAttributeIconSize 0
hide footbox
actor User
participant ":InputManager" as IM
participant ":InputParser" as IP
participant ":AlertCommand" as AC
participant ":AlertParser" as AP
participant ":BudgetManager" as BM
participant ":Alert" as A
participant ":Ui" as UI

User -> IM: Enters "alert 500" command
activate IM
IM -> IP: parseInput(userInput)
activate IP
create AC
IP -> AC: initialize with description
activate AC
AC --> IP
deactivate AC
IP --> IM: Return AlertCommand object
deactivate IP

IM -> AC: execute(budgetManager)
activate AC
create AP
AC -> AP: new AlertParser(description)
activate AP
AP --> AC
deactivate AP
AC -> AP: parse()
activate AP
AP --> AC: Return alert amount
deactivate AP
AC -> BM: setBudgetAlert(amount)
activate BM
BM -> A: setAlert(amount)
activate A
alt amount > 0
A -> UI: printSetBudgetAlert(amount, false)
activate UI
UI --> A
deactivate UI
else amount == 0
A -> UI: printRemoveBudgetAlert()
activate UI
UI --> A
deactivate UI
end
A-->BM
deactivate A



BM -> A:checkAlert(totalExpenses)
activate A
opt Total expenses exceed alert amount
A -> UI: printCheckAlert(totalExpenses, alertAmount)
activate UI
UI --> A
deactivate UI
else Total expenses equals alert amount
A -> UI: printHitAlert(totalExpenses)
activate UI
UI --> A
deactivate UI
end
A --> BM
deactivate A
BM-->AC
deactivate BM
AC --> IM
deactivate AC
IM --> User: Show success message
deactivate IM
@enduml