@startuml
hide circle
skinparam classAttributeIconSize 0
hide footbox
actor User
participant ":InputManager" as IM
participant ":InputParser" as IP
participant ":AddExpenseCommand" as AEC
participant ":AddParser" as AP
participant ":BudgetManager" as BM



User -> IM: Enters "add 50 c/ Overall d/ cab fares t/ Jan 15 2025 at 11:30" command
activate IM
IM -> IP: parseInput(userInput)
activate IP
create AEC
IP -> AEC: initialize with (amount, category, description, time)
activate AEC
AEC --> IP
deactivate AEC
IP --> IM: Return AddExpenseCommand object
deactivate IP
IM -> AEC: execute(budgetManager)
activate AEC
Create AP
AEC -> AP: new AddParser(description)
activate AP
AP --> AEC
deactivate AP
AEC -> AP: parse()
activate AP
AP --> AEC: Return parsed components [amount, category, description, time]
deactivate AP

deactivate AP
box AEC #LightGreen
AEC -> BM: addExpenseToBudget(category, amount, description, time)
activate BM
BM --> AEC:
deactivate BM
AEC --> IM:
end box

deactivate AEC

IM --> User: Show success message
deactivate IM
@enduml