@startuml
hide circle
skinparam classAttributeIconSize 0
hide footbox

participant ":CheckBudgetCommand" as CBC
participant ":BudgetManager" as BM
participant ":Budget" as B
participant ":Ui" as UI

activate CBC
CBC -> BM: checkBudget(category)
activate BM

alt category is empty or blank
    BM -> BM: budgets.get("Overall")
    activate BM
    note right of BM: Retrieve Overall budget
    BM --> BM
    deactivate BM

    BM -> B: getLimit()
    activate B
    B --> BM: totalBudget
    deactivate B

    BM -> B: getTotalExpenses()
    activate B
    B --> BM: Return total amount spent
    deactivate B

    BM -> UI: printCheckBudget("", totalBudget, spent, remaining)
    activate UI
    UI --> BM
    deactivate UI

else category provided
    opt category does not exist
        BM -> UI: printBudgetNotFound(category)
        activate UI
        UI --> BM
        deactivate UI

        BM --> CBC
        end
        BM -> BM: budgets.get(category)
        activate BM
        note right of BM: Retrieve category budget
        BM --> BM
        deactivate BM

        BM -> B: getLimit()
        activate B
        B --> BM: totalBudget
        deactivate B

        BM -> B: getTotalExpenses()
        activate B
        B --> BM: Return total amount spent
        deactivate B

        BM -> UI: printCheckBudget(category, totalBudget, spent, remaining)
        activate UI
        UI --> BM
        deactivate UI

end

BM --> CBC
deactivate BM
@enduml