@startuml
hide footbox

participant ":ListCommand" as LC
participant ":ListParser" as P
participant ":BudgetManager" as BM
participant ":Budget" as B
participant ":Ui"
participant ":DateTimeParser" as DTP

activate LC
create P
LC -> P : new ListParser(description)
activate P
P --> LC : ListParser
deactivate P

LC -> P : parse()
activate P
P --> LC : [start, end]
deactivate P

alt start and end are both empty
    LC -> BM : listAllExpenses()
    activate BM
    BM -> B : get("Overall")
    activate B
    B --> BM : Budget
    deactivate B
    BM -> B : printExpenses()
    activate B

    alt expenses.isEmpty()
        B -> Ui : printNoExpense()
        activate Ui
        Ui --> B
        deactivate Ui
    else
        B -> Ui : printExpensesList(expenses)
        activate Ui
        Ui --> B
        deactivate Ui
    end

    B --> BM
    deactivate B
    BM --> LC
    deactivate BM

else start or end is provided
    LC -> BM : listAllExpenses()
    activate BM
    BM -> B : get("Overall")
    activate B
    B --> BM : Budget
    deactivate B
    BM -> B : printExpenses(start,end)
    activate B
    alt expenses.isEmpty()
        B -> Ui : printNoExpense()
        activate Ui
        Ui --> B
        deactivate Ui
    else
        opt start is provided
            B -> DTP : parseOrDefault(start)
            activate DTP
            DTP --> B : startDate
            deactivate DTP

            B -> DTP : parseOrDefaultBooleanReturn(start)
            activate DTP
            DTP --> B : boolean
            deactivate DTP
        end

        opt end is provided
            B -> DTP : parseOrDefault(end)
            activate DTP
            DTP --> B : endDate
            deactivate DTP

            B -> DTP : parseOrDefaultBooleanReturn(end)
            activate DTP
            DTP --> B : boolean
            deactivate DTP
        end

        B -> Ui : printExpensesList(expenses, start, end)
        activate Ui
        Ui --> B
        deactivate Ui
    end

    B --> BM
    deactivate B
    BM --> LC
    deactivate BM
end

deactivate LC
@enduml