@startuml
hide circle
skinparam classAttributeIconSize 0
hide footbox

actor User
participant ":InputManager" as IM
participant ":InputParser" as IP
participant ":SummaryCommand" as SC
participant ":SummaryParser" as SP
participant ":BudgetSummary" as BS
participant ":UI" as UI
participant ":BudgetManager" as BM

User -> IM: Enters "summary"
activate IM
IM -> IP: parseInput(userInput)
activate IP
create SC
IP -> SC: initialize with (description)
activate SC
SC --> IP
deactivate SC
IP --> IM: Return SummaryCommand object
deactivate IP
IM -> SC: execute(budgetManager)
activate SC
create SP
SC -> SP: new SummaryParser(description, budgetManager)
activate SP
SP --> SC
deactivate SP

SC -> SP: parse()
activate SP
SP --> SC : Return categories to display

deactivate SP


create BS
SC -> BS: new BudgetSummary(budgetManager)
activate BS
BS --> SC
deactivate BS

alt No categories provided
SC -> BS: summariseBudget()
activate BS
BS -> BM: getBudgets()
activate BM
BM --> BS: Return budgets
deactivate BM
BS -> UI: printBudgetSummary()
activate UI
UI --> BS: summary displayed
deactivate UI
BS--> SC
deactivate BS

else Specific categories provided
SC -> BS: summariseBudget(categories)
activate BS
loop For each specified category
BS -> BM: getBudgets().get(category)
activate BM
BM --> BS: Return specific budget category
deactivate BM
end
BS -> UI: printBudgetSummary()
activate UI
UI --> BS: summary displayed
deactivate UI
BS--> SC
deactivate BS
end





deactivate BM
SC --> IM:

deactivate SC
IM --> User: Show summary result
deactivate IM
@enduml
